// <auto-generated />
using System;
using InsulinResistanceApp.Server.Dane;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsulinResistanceApp.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240416080448_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("InsulinResistanceApp.Shared.Kategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kategorie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nazwa = "Owoce"
                        },
                        new
                        {
                            Id = 2,
                            Nazwa = "Warzywa"
                        },
                        new
                        {
                            Id = 3,
                            Nazwa = "Nabiał"
                        },
                        new
                        {
                            Id = 4,
                            Nazwa = "Mięso"
                        },
                        new
                        {
                            Id = 5,
                            Nazwa = "Ryby"
                        },
                        new
                        {
                            Id = 6,
                            Nazwa = "Produkty zbożowe"
                        },
                        new
                        {
                            Id = 7,
                            Nazwa = "Słodycze"
                        },
                        new
                        {
                            Id = 8,
                            Nazwa = "Napoje"
                        },
                        new
                        {
                            Id = 9,
                            Nazwa = "Inne"
                        });
                });

            modelBuilder.Entity("InsulinResistanceApp.Shared.Produkt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("KategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("bialko")
                        .HasColumnType("int");

                    b.Property<int>("indeksglikemiczny")
                        .HasColumnType("int");

                    b.Property<int>("kcal")
                        .HasColumnType("int");

                    b.Property<int>("tluszcze")
                        .HasColumnType("int");

                    b.Property<int>("weglowodany")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KategoriaId");

                    b.ToTable("Produkty");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KategoriaId = 1,
                            Nazwa = "Jabłka",
                            bialko = 0,
                            indeksglikemiczny = 38,
                            kcal = 52,
                            tluszcze = 0,
                            weglowodany = 14
                        },
                        new
                        {
                            Id = 2,
                            KategoriaId = 1,
                            Nazwa = "Banany",
                            bialko = 1,
                            indeksglikemiczny = 51,
                            kcal = 89,
                            tluszcze = 0,
                            weglowodany = 23
                        },
                        new
                        {
                            Id = 3,
                            KategoriaId = 1,
                            Nazwa = "Pomarańcze",
                            bialko = 1,
                            indeksglikemiczny = 43,
                            kcal = 43,
                            tluszcze = 0,
                            weglowodany = 9
                        },
                        new
                        {
                            Id = 4,
                            KategoriaId = 1,
                            Nazwa = "Awokado",
                            bialko = 2,
                            indeksglikemiczny = 10,
                            kcal = 160,
                            tluszcze = 15,
                            weglowodany = 9
                        },
                        new
                        {
                            Id = 5,
                            KategoriaId = 6,
                            Nazwa = "Chleb pełnoziarnisty",
                            bialko = 10,
                            indeksglikemiczny = 50,
                            kcal = 250,
                            tluszcze = 4,
                            weglowodany = 45
                        },
                        new
                        {
                            Id = 6,
                            KategoriaId = 9,
                            Nazwa = "Masło orzechowe",
                            bialko = 25,
                            indeksglikemiczny = 30,
                            kcal = 588,
                            tluszcze = 50,
                            weglowodany = 20
                        },
                        new
                        {
                            Id = 7,
                            KategoriaId = 3,
                            Nazwa = "Jogurt naturalny",
                            bialko = 10,
                            indeksglikemiczny = 36,
                            kcal = 61,
                            tluszcze = 3,
                            weglowodany = 4
                        },
                        new
                        {
                            Id = 8,
                            KategoriaId = 3,
                            Nazwa = "Mleko 2%",
                            bialko = 3,
                            indeksglikemiczny = 30,
                            kcal = 50,
                            tluszcze = 2,
                            weglowodany = 5
                        },
                        new
                        {
                            Id = 9,
                            KategoriaId = 3,
                            Nazwa = "Twaróg",
                            bialko = 18,
                            indeksglikemiczny = 45,
                            kcal = 174,
                            tluszcze = 9,
                            weglowodany = 3
                        },
                        new
                        {
                            Id = 10,
                            KategoriaId = 4,
                            Nazwa = "Kurczak",
                            bialko = 27,
                            indeksglikemiczny = 0,
                            kcal = 239,
                            tluszcze = 14,
                            weglowodany = 0
                        },
                        new
                        {
                            Id = 11,
                            KategoriaId = 5,
                            Nazwa = "Łosoś",
                            bialko = 20,
                            indeksglikemiczny = 0,
                            kcal = 208,
                            tluszcze = 13,
                            weglowodany = 0
                        },
                        new
                        {
                            Id = 12,
                            KategoriaId = 3,
                            Nazwa = "Jajko",
                            bialko = 6,
                            indeksglikemiczny = 0,
                            kcal = 68,
                            tluszcze = 5,
                            weglowodany = 1
                        },
                        new
                        {
                            Id = 13,
                            KategoriaId = 6,
                            Nazwa = "Ryż brązowy",
                            bialko = 2,
                            indeksglikemiczny = 50,
                            kcal = 111,
                            tluszcze = 1,
                            weglowodany = 23
                        },
                        new
                        {
                            Id = 14,
                            KategoriaId = 6,
                            Nazwa = "Makaron pełnoziarnisty",
                            bialko = 7,
                            indeksglikemiczny = 40,
                            kcal = 158,
                            tluszcze = 1,
                            weglowodany = 31
                        },
                        new
                        {
                            Id = 15,
                            KategoriaId = 9,
                            Nazwa = "Oliwa z oliwek",
                            bialko = 0,
                            indeksglikemiczny = 0,
                            kcal = 884,
                            tluszcze = 100,
                            weglowodany = 0
                        },
                        new
                        {
                            Id = 16,
                            KategoriaId = 9,
                            Nazwa = "Orzechy włoskie",
                            bialko = 16,
                            indeksglikemiczny = 15,
                            kcal = 654,
                            tluszcze = 65,
                            weglowodany = 14
                        },
                        new
                        {
                            Id = 17,
                            KategoriaId = 6,
                            Nazwa = "Kasza jaglana",
                            bialko = 8,
                            indeksglikemiczny = 40,
                            kcal = 346,
                            tluszcze = 1,
                            weglowodany = 77
                        },
                        new
                        {
                            Id = 18,
                            KategoriaId = 6,
                            Nazwa = "Owies",
                            bialko = 17,
                            indeksglikemiczny = 50,
                            kcal = 389,
                            tluszcze = 7,
                            weglowodany = 66
                        },
                        new
                        {
                            Id = 19,
                            KategoriaId = 7,
                            Nazwa = "Czekolada gorzka",
                            bialko = 5,
                            indeksglikemiczny = 22,
                            kcal = 546,
                            tluszcze = 32,
                            weglowodany = 31
                        },
                        new
                        {
                            Id = 20,
                            KategoriaId = 2,
                            Nazwa = "Czosnek",
                            bialko = 6,
                            indeksglikemiczny = 30,
                            kcal = 149,
                            tluszcze = 0,
                            weglowodany = 33
                        },
                        new
                        {
                            Id = 21,
                            KategoriaId = 2,
                            Nazwa = "Cebula",
                            bialko = 1,
                            indeksglikemiczny = 10,
                            kcal = 40,
                            tluszcze = 0,
                            weglowodany = 9
                        },
                        new
                        {
                            Id = 22,
                            KategoriaId = 2,
                            Nazwa = "Brokuły",
                            bialko = 3,
                            indeksglikemiczny = 10,
                            kcal = 34,
                            tluszcze = 0,
                            weglowodany = 7
                        },
                        new
                        {
                            Id = 23,
                            KategoriaId = 2,
                            Nazwa = "Papryka czerwona",
                            bialko = 1,
                            indeksglikemiczny = 10,
                            kcal = 31,
                            tluszcze = 0,
                            weglowodany = 7
                        },
                        new
                        {
                            Id = 24,
                            KategoriaId = 2,
                            Nazwa = "Pomidor",
                            bialko = 1,
                            indeksglikemiczny = 10,
                            kcal = 18,
                            tluszcze = 0,
                            weglowodany = 4
                        },
                        new
                        {
                            Id = 25,
                            KategoriaId = 9,
                            Nazwa = "Tymianek",
                            bialko = 9,
                            indeksglikemiczny = 15,
                            kcal = 276,
                            tluszcze = 7,
                            weglowodany = 64
                        },
                        new
                        {
                            Id = 26,
                            KategoriaId = 9,
                            Nazwa = "Sól",
                            bialko = 0,
                            indeksglikemiczny = 0,
                            kcal = 0,
                            tluszcze = 0,
                            weglowodany = 0
                        },
                        new
                        {
                            Id = 27,
                            KategoriaId = 9,
                            Nazwa = "Pieprz",
                            bialko = 10,
                            indeksglikemiczny = 15,
                            kcal = 251,
                            tluszcze = 3,
                            weglowodany = 64
                        },
                        new
                        {
                            Id = 28,
                            KategoriaId = 9,
                            Nazwa = "Kurkuma",
                            bialko = 8,
                            indeksglikemiczny = 0,
                            kcal = 354,
                            tluszcze = 10,
                            weglowodany = 65
                        },
                        new
                        {
                            Id = 29,
                            KategoriaId = 2,
                            Nazwa = "Chili",
                            bialko = 2,
                            indeksglikemiczny = 10,
                            kcal = 40,
                            tluszcze = 0,
                            weglowodany = 9
                        },
                        new
                        {
                            Id = 30,
                            KategoriaId = 8,
                            Nazwa = "Kawa",
                            bialko = 0,
                            indeksglikemiczny = 0,
                            kcal = 1,
                            tluszcze = 0,
                            weglowodany = 0
                        },
                        new
                        {
                            Id = 31,
                            KategoriaId = 8,
                            Nazwa = "Herbata",
                            bialko = 0,
                            indeksglikemiczny = 0,
                            kcal = 1,
                            tluszcze = 0,
                            weglowodany = 0
                        },
                        new
                        {
                            Id = 32,
                            KategoriaId = 7,
                            Nazwa = "Miod",
                            bialko = 0,
                            indeksglikemiczny = 50,
                            kcal = 304,
                            tluszcze = 0,
                            weglowodany = 82
                        },
                        new
                        {
                            Id = 33,
                            KategoriaId = 1,
                            Nazwa = "Cytryna",
                            bialko = 1,
                            indeksglikemiczny = 20,
                            kcal = 29,
                            tluszcze = 0,
                            weglowodany = 9
                        },
                        new
                        {
                            Id = 34,
                            KategoriaId = 1,
                            Nazwa = "Liczi",
                            bialko = 0,
                            indeksglikemiczny = 50,
                            kcal = 66,
                            tluszcze = 0,
                            weglowodany = 16
                        },
                        new
                        {
                            Id = 35,
                            KategoriaId = 1,
                            Nazwa = "Winogrona",
                            bialko = 1,
                            indeksglikemiczny = 59,
                            kcal = 69,
                            tluszcze = 0,
                            weglowodany = 18
                        },
                        new
                        {
                            Id = 36,
                            KategoriaId = 1,
                            Nazwa = "Truskawki",
                            bialko = 1,
                            indeksglikemiczny = 25,
                            kcal = 32,
                            tluszcze = 0,
                            weglowodany = 8
                        },
                        new
                        {
                            Id = 37,
                            KategoriaId = 9,
                            Nazwa = "Pizza Margherita",
                            bialko = 12,
                            indeksglikemiczny = 30,
                            kcal = 266,
                            tluszcze = 9,
                            weglowodany = 32
                        },
                        new
                        {
                            Id = 38,
                            KategoriaId = 2,
                            Nazwa = "Sałatka grecka",
                            bialko = 7,
                            indeksglikemiczny = 15,
                            kcal = 159,
                            tluszcze = 10,
                            weglowodany = 11
                        },
                        new
                        {
                            Id = 39,
                            KategoriaId = 7,
                            Nazwa = "Czekolada mleczna",
                            bialko = 8,
                            indeksglikemiczny = 40,
                            kcal = 535,
                            tluszcze = 30,
                            weglowodany = 58
                        },
                        new
                        {
                            Id = 40,
                            KategoriaId = 4,
                            Nazwa = "Burger wołowy",
                            bialko = 12,
                            indeksglikemiczny = 30,
                            kcal = 254,
                            tluszcze = 14,
                            weglowodany = 28
                        },
                        new
                        {
                            Id = 41,
                            KategoriaId = 4,
                            Nazwa = "Kanapka z szynką",
                            bialko = 12,
                            indeksglikemiczny = 30,
                            kcal = 210,
                            tluszcze = 8,
                            weglowodany = 23
                        },
                        new
                        {
                            Id = 42,
                            KategoriaId = 6,
                            Nazwa = "Owsianka z miodem",
                            bialko = 6,
                            indeksglikemiczny = 40,
                            kcal = 230,
                            tluszcze = 4,
                            weglowodany = 50
                        },
                        new
                        {
                            Id = 43,
                            KategoriaId = 4,
                            Nazwa = "Kiełbasa",
                            bialko = 15,
                            indeksglikemiczny = 0,
                            kcal = 331,
                            tluszcze = 30,
                            weglowodany = 2
                        },
                        new
                        {
                            Id = 44,
                            KategoriaId = 7,
                            Nazwa = "Lody waniliowe",
                            bialko = 3,
                            indeksglikemiczny = 40,
                            kcal = 207,
                            tluszcze = 11,
                            weglowodany = 25
                        },
                        new
                        {
                            Id = 45,
                            KategoriaId = 7,
                            Nazwa = "Chipsy ziemniaczane",
                            bialko = 6,
                            indeksglikemiczny = 75,
                            kcal = 536,
                            tluszcze = 34,
                            weglowodany = 50
                        },
                        new
                        {
                            Id = 46,
                            KategoriaId = 8,
                            Nazwa = "Herbata z cukrem",
                            bialko = 0,
                            indeksglikemiczny = 65,
                            kcal = 43,
                            tluszcze = 0,
                            weglowodany = 11
                        },
                        new
                        {
                            Id = 47,
                            KategoriaId = 8,
                            Nazwa = "Kawa z mlekiem i cukrem",
                            bialko = 1,
                            indeksglikemiczny = 45,
                            kcal = 43,
                            tluszcze = 1,
                            weglowodany = 7
                        },
                        new
                        {
                            Id = 48,
                            KategoriaId = 8,
                            Nazwa = "Coca-Cola",
                            bialko = 0,
                            indeksglikemiczny = 63,
                            kcal = 42,
                            tluszcze = 0,
                            weglowodany = 11
                        },
                        new
                        {
                            Id = 49,
                            KategoriaId = 2,
                            Nazwa = "Sałatka owocowa z majonezem",
                            bialko = 3,
                            indeksglikemiczny = 40,
                            kcal = 210,
                            tluszcze = 5,
                            weglowodany = 45
                        },
                        new
                        {
                            Id = 50,
                            KategoriaId = 7,
                            Nazwa = "Ciastka czekoladowe",
                            bialko = 5,
                            indeksglikemiczny = 50,
                            kcal = 480,
                            tluszcze = 22,
                            weglowodany = 63
                        },
                        new
                        {
                            Id = 51,
                            KategoriaId = 7,
                            Nazwa = "Orzechy nerkowca",
                            bialko = 18,
                            indeksglikemiczny = 20,
                            kcal = 553,
                            tluszcze = 44,
                            weglowodany = 30
                        },
                        new
                        {
                            Id = 52,
                            KategoriaId = 7,
                            Nazwa = "Lody czekoladowe",
                            bialko = 3,
                            indeksglikemiczny = 40,
                            kcal = 216,
                            tluszcze = 12,
                            weglowodany = 28
                        },
                        new
                        {
                            Id = 53,
                            KategoriaId = 3,
                            Nazwa = "Jogurt owocowy",
                            bialko = 4,
                            indeksglikemiczny = 35,
                            kcal = 85,
                            tluszcze = 2,
                            weglowodany = 15
                        },
                        new
                        {
                            Id = 54,
                            KategoriaId = 4,
                            Nazwa = "Kurczak pieczony",
                            bialko = 31,
                            indeksglikemiczny = 0,
                            kcal = 165,
                            tluszcze = 3,
                            weglowodany = 0
                        },
                        new
                        {
                            Id = 55,
                            KategoriaId = 5,
                            Nazwa = "Makaron biały",
                            bialko = 5,
                            indeksglikemiczny = 50,
                            kcal = 158,
                            tluszcze = 1,
                            weglowodany = 31
                        },
                        new
                        {
                            Id = 56,
                            KategoriaId = 7,
                            Nazwa = "Chipsy kukurydziane",
                            bialko = 6,
                            indeksglikemiczny = 85,
                            kcal = 536,
                            tluszcze = 35,
                            weglowodany = 51
                        },
                        new
                        {
                            Id = 57,
                            KategoriaId = 8,
                            Nazwa = "Sok pomarańczowy",
                            bialko = 1,
                            indeksglikemiczny = 40,
                            kcal = 45,
                            tluszcze = 0,
                            weglowodany = 11
                        },
                        new
                        {
                            Id = 58,
                            KategoriaId = 7,
                            Nazwa = "Pączek",
                            bialko = 4,
                            indeksglikemiczny = 70,
                            kcal = 280,
                            tluszcze = 16,
                            weglowodany = 31
                        },
                        new
                        {
                            Id = 59,
                            KategoriaId = 7,
                            Nazwa = "Czekolada gorzka 70%",
                            bialko = 7,
                            indeksglikemiczny = 30,
                            kcal = 581,
                            tluszcze = 42,
                            weglowodany = 45
                        },
                        new
                        {
                            Id = 60,
                            KategoriaId = 5,
                            Nazwa = "Ryż biały",
                            bialko = 3,
                            indeksglikemiczny = 70,
                            kcal = 130,
                            tluszcze = 0,
                            weglowodany = 28
                        },
                        new
                        {
                            Id = 61,
                            KategoriaId = 3,
                            Nazwa = "Ser żółty",
                            bialko = 25,
                            indeksglikemiczny = 0,
                            kcal = 402,
                            tluszcze = 33,
                            weglowodany = 2
                        },
                        new
                        {
                            Id = 62,
                            KategoriaId = 8,
                            Nazwa = "Piwo",
                            bialko = 1,
                            indeksglikemiczny = 55,
                            kcal = 43,
                            tluszcze = 0,
                            weglowodany = 3
                        },
                        new
                        {
                            Id = 63,
                            KategoriaId = 8,
                            Nazwa = "Wódka",
                            bialko = 0,
                            indeksglikemiczny = 0,
                            kcal = 231,
                            tluszcze = 0,
                            weglowodany = 0
                        },
                        new
                        {
                            Id = 64,
                            KategoriaId = 2,
                            Nazwa = "Szpinak",
                            bialko = 2,
                            indeksglikemiczny = 15,
                            kcal = 23,
                            tluszcze = 0,
                            weglowodany = 3
                        },
                        new
                        {
                            Id = 65,
                            KategoriaId = 4,
                            Nazwa = "Mleko kozie",
                            bialko = 3,
                            indeksglikemiczny = 30,
                            kcal = 68,
                            tluszcze = 5,
                            weglowodany = 4
                        },
                        new
                        {
                            Id = 66,
                            KategoriaId = 9,
                            Nazwa = "Olej rzepakowy",
                            bialko = 0,
                            indeksglikemiczny = 0,
                            kcal = 884,
                            tluszcze = 100,
                            weglowodany = 0
                        },
                        new
                        {
                            Id = 67,
                            KategoriaId = 4,
                            Nazwa = "Mleko sojowe",
                            bialko = 3,
                            indeksglikemiczny = 20,
                            kcal = 33,
                            tluszcze = 1,
                            weglowodany = 1
                        },
                        new
                        {
                            Id = 68,
                            KategoriaId = 4,
                            Nazwa = "Tofu",
                            bialko = 8,
                            indeksglikemiczny = 15,
                            kcal = 76,
                            tluszcze = 4,
                            weglowodany = 1
                        },
                        new
                        {
                            Id = 69,
                            KategoriaId = 5,
                            Nazwa = "Quinoa",
                            bialko = 4,
                            indeksglikemiczny = 53,
                            kcal = 120,
                            tluszcze = 2,
                            weglowodany = 21
                        },
                        new
                        {
                            Id = 70,
                            KategoriaId = 1,
                            Nazwa = "Jabłka suszone",
                            bialko = 2,
                            indeksglikemiczny = 38,
                            kcal = 243,
                            tluszcze = 0,
                            weglowodany = 63
                        },
                        new
                        {
                            Id = 71,
                            KategoriaId = 1,
                            Nazwa = "Mango",
                            bialko = 1,
                            indeksglikemiczny = 51,
                            kcal = 60,
                            tluszcze = 0,
                            weglowodany = 15
                        },
                        new
                        {
                            Id = 72,
                            KategoriaId = 7,
                            Nazwa = "Orzechy laskowe",
                            bialko = 15,
                            indeksglikemiczny = 15,
                            kcal = 628,
                            tluszcze = 61,
                            weglowodany = 20
                        },
                        new
                        {
                            Id = 73,
                            KategoriaId = 8,
                            Nazwa = "Kawa z syropem waniliowym",
                            bialko = 3,
                            indeksglikemiczny = 45,
                            kcal = 293,
                            tluszcze = 7,
                            weglowodany = 42
                        },
                        new
                        {
                            Id = 74,
                            KategoriaId = 2,
                            Nazwa = "Kiełki lucerny",
                            bialko = 4,
                            indeksglikemiczny = 10,
                            kcal = 23,
                            tluszcze = 0,
                            weglowodany = 4
                        },
                        new
                        {
                            Id = 75,
                            KategoriaId = 5,
                            Nazwa = "Kasza gryczana",
                            bialko = 13,
                            indeksglikemiczny = 50,
                            kcal = 335,
                            tluszcze = 3,
                            weglowodany = 70
                        },
                        new
                        {
                            Id = 76,
                            KategoriaId = 2,
                            Nazwa = "Kapusta kiszona",
                            bialko = 1,
                            indeksglikemiczny = 10,
                            kcal = 19,
                            tluszcze = 0,
                            weglowodany = 4
                        },
                        new
                        {
                            Id = 77,
                            KategoriaId = 8,
                            Nazwa = "Woda gazowana",
                            bialko = 0,
                            indeksglikemiczny = 0,
                            kcal = 0,
                            tluszcze = 0,
                            weglowodany = 0
                        },
                        new
                        {
                            Id = 78,
                            KategoriaId = 2,
                            Nazwa = "Mięta",
                            bialko = 4,
                            indeksglikemiczny = 15,
                            kcal = 70,
                            tluszcze = 1,
                            weglowodany = 14
                        },
                        new
                        {
                            Id = 79,
                            KategoriaId = 4,
                            Nazwa = "Miód",
                            bialko = 0,
                            indeksglikemiczny = 50,
                            kcal = 304,
                            tluszcze = 0,
                            weglowodany = 82
                        },
                        new
                        {
                            Id = 80,
                            KategoriaId = 2,
                            Nazwa = "Kurkuma",
                            bialko = 8,
                            indeksglikemiczny = 0,
                            kcal = 354,
                            tluszcze = 10,
                            weglowodany = 65
                        },
                        new
                        {
                            Id = 81,
                            KategoriaId = 4,
                            Nazwa = "Sardynki w oleju",
                            bialko = 25,
                            indeksglikemiczny = 0,
                            kcal = 208,
                            tluszcze = 11,
                            weglowodany = 0
                        },
                        new
                        {
                            Id = 82,
                            KategoriaId = 4,
                            Nazwa = "Krewetki",
                            bialko = 18,
                            indeksglikemiczny = 0,
                            kcal = 85,
                            tluszcze = 1,
                            weglowodany = 0
                        },
                        new
                        {
                            Id = 83,
                            KategoriaId = 1,
                            Nazwa = "Czarna porzeczka",
                            bialko = 1,
                            indeksglikemiczny = 25,
                            kcal = 56,
                            tluszcze = 0,
                            weglowodany = 14
                        },
                        new
                        {
                            Id = 84,
                            KategoriaId = 4,
                            Nazwa = "Sushi z łososiem",
                            bialko = 4,
                            indeksglikemiczny = 45,
                            kcal = 132,
                            tluszcze = 3,
                            weglowodany = 22
                        },
                        new
                        {
                            Id = 85,
                            KategoriaId = 1,
                            Nazwa = "Awokado",
                            bialko = 2,
                            indeksglikemiczny = 10,
                            kcal = 160,
                            tluszcze = 15,
                            weglowodany = 9
                        },
                        new
                        {
                            Id = 86,
                            KategoriaId = 7,
                            Nazwa = "Migdały",
                            bialko = 21,
                            indeksglikemiczny = 0,
                            kcal = 575,
                            tluszcze = 49,
                            weglowodany = 22
                        },
                        new
                        {
                            Id = 87,
                            KategoriaId = 8,
                            Nazwa = "Pomarańczowy sok",
                            bialko = 1,
                            indeksglikemiczny = 45,
                            kcal = 45,
                            tluszcze = 0,
                            weglowodany = 11
                        },
                        new
                        {
                            Id = 88,
                            KategoriaId = 5,
                            Nazwa = "Granola",
                            bialko = 12,
                            indeksglikemiczny = 55,
                            kcal = 471,
                            tluszcze = 20,
                            weglowodany = 58
                        },
                        new
                        {
                            Id = 89,
                            KategoriaId = 4,
                            Nazwa = "Kokosowe mleko",
                            bialko = 2,
                            indeksglikemiczny = 45,
                            kcal = 230,
                            tluszcze = 23,
                            weglowodany = 6
                        },
                        new
                        {
                            Id = 90,
                            KategoriaId = 1,
                            Nazwa = "Banany suszone",
                            bialko = 3,
                            indeksglikemiczny = 65,
                            kcal = 346,
                            tluszcze = 1,
                            weglowodany = 87
                        },
                        new
                        {
                            Id = 91,
                            KategoriaId = 1,
                            Nazwa = "Grapefruit",
                            bialko = 1,
                            indeksglikemiczny = 25,
                            kcal = 42,
                            tluszcze = 0,
                            weglowodany = 11
                        },
                        new
                        {
                            Id = 92,
                            KategoriaId = 2,
                            Nazwa = "Kurkuma w proszku",
                            bialko = 9,
                            indeksglikemiczny = 0,
                            kcal = 312,
                            tluszcze = 3,
                            weglowodany = 68
                        },
                        new
                        {
                            Id = 93,
                            KategoriaId = 8,
                            Nazwa = "Herbata zielona",
                            bialko = 0,
                            indeksglikemiczny = 0,
                            kcal = 1,
                            tluszcze = 0,
                            weglowodany = 0
                        },
                        new
                        {
                            Id = 94,
                            KategoriaId = 8,
                            Nazwa = "Woda kokosowa",
                            bialko = 0,
                            indeksglikemiczny = 45,
                            kcal = 19,
                            tluszcze = 0,
                            weglowodany = 4
                        },
                        new
                        {
                            Id = 95,
                            KategoriaId = 2,
                            Nazwa = "Czosnek",
                            bialko = 6,
                            indeksglikemiczny = 30,
                            kcal = 149,
                            tluszcze = 0,
                            weglowodany = 33
                        },
                        new
                        {
                            Id = 96,
                            KategoriaId = 2,
                            Nazwa = "Bób",
                            bialko = 27,
                            indeksglikemiczny = 20,
                            kcal = 341,
                            tluszcze = 1,
                            weglowodany = 63
                        },
                        new
                        {
                            Id = 97,
                            KategoriaId = 2,
                            Nazwa = "Pietruszka",
                            bialko = 4,
                            indeksglikemiczny = 20,
                            kcal = 45,
                            tluszcze = 0,
                            weglowodany = 10
                        },
                        new
                        {
                            Id = 98,
                            KategoriaId = 3,
                            Nazwa = "Jogurt naturalny",
                            bialko = 10,
                            indeksglikemiczny = 36,
                            kcal = 61,
                            tluszcze = 3,
                            weglowodany = 4
                        },
                        new
                        {
                            Id = 99,
                            KategoriaId = 6,
                            Nazwa = "Ryż basmati",
                            bialko = 3,
                            indeksglikemiczny = 58,
                            kcal = 130,
                            tluszcze = 0,
                            weglowodany = 28
                        },
                        new
                        {
                            Id = 100,
                            KategoriaId = 3,
                            Nazwa = "Migdałowe mleko",
                            bialko = 1,
                            indeksglikemiczny = 25,
                            kcal = 56,
                            tluszcze = 5,
                            weglowodany = 1
                        },
                        new
                        {
                            Id = 101,
                            KategoriaId = 8,
                            Nazwa = "Sok jabłkowy",
                            bialko = 0,
                            indeksglikemiczny = 40,
                            kcal = 46,
                            tluszcze = 0,
                            weglowodany = 12
                        },
                        new
                        {
                            Id = 102,
                            KategoriaId = 9,
                            Nazwa = "Tahini",
                            bialko = 17,
                            indeksglikemiczny = 0,
                            kcal = 595,
                            tluszcze = 53,
                            weglowodany = 17
                        },
                        new
                        {
                            Id = 103,
                            KategoriaId = 9,
                            Nazwa = "Oliwa z oliwek",
                            bialko = 0,
                            indeksglikemiczny = 0,
                            kcal = 884,
                            tluszcze = 100,
                            weglowodany = 0
                        },
                        new
                        {
                            Id = 104,
                            KategoriaId = 1,
                            Nazwa = "Truskawki",
                            bialko = 1,
                            indeksglikemiczny = 25,
                            kcal = 32,
                            tluszcze = 0,
                            weglowodany = 8
                        },
                        new
                        {
                            Id = 105,
                            KategoriaId = 1,
                            Nazwa = "Jabłko",
                            bialko = 0,
                            indeksglikemiczny = 38,
                            kcal = 52,
                            tluszcze = 0,
                            weglowodany = 14
                        },
                        new
                        {
                            Id = 106,
                            KategoriaId = 1,
                            Nazwa = "Mango",
                            bialko = 1,
                            indeksglikemiczny = 51,
                            kcal = 60,
                            tluszcze = 0,
                            weglowodany = 15
                        },
                        new
                        {
                            Id = 107,
                            KategoriaId = 1,
                            Nazwa = "Maliny",
                            bialko = 1,
                            indeksglikemiczny = 25,
                            kcal = 52,
                            tluszcze = 0,
                            weglowodany = 12
                        },
                        new
                        {
                            Id = 108,
                            KategoriaId = 1,
                            Nazwa = "Ananas",
                            bialko = 0,
                            indeksglikemiczny = 66,
                            kcal = 50,
                            tluszcze = 0,
                            weglowodany = 13
                        },
                        new
                        {
                            Id = 109,
                            KategoriaId = 2,
                            Nazwa = "Ogórek",
                            bialko = 1,
                            indeksglikemiczny = 10,
                            kcal = 15,
                            tluszcze = 0,
                            weglowodany = 3
                        },
                        new
                        {
                            Id = 110,
                            KategoriaId = 2,
                            Nazwa = "Marchew",
                            bialko = 1,
                            indeksglikemiczny = 35,
                            kcal = 41,
                            tluszcze = 0,
                            weglowodany = 10
                        },
                        new
                        {
                            Id = 111,
                            KategoriaId = 2,
                            Nazwa = "Szpinak",
                            bialko = 2,
                            indeksglikemiczny = 15,
                            kcal = 23,
                            tluszcze = 0,
                            weglowodany = 3
                        },
                        new
                        {
                            Id = 112,
                            KategoriaId = 2,
                            Nazwa = "Banan",
                            bialko = 1,
                            indeksglikemiczny = 51,
                            kcal = 89,
                            tluszcze = 0,
                            weglowodany = 23
                        },
                        new
                        {
                            Id = 113,
                            KategoriaId = 6,
                            Nazwa = "Kasza jaglana",
                            bialko = 8,
                            indeksglikemiczny = 40,
                            kcal = 346,
                            tluszcze = 1,
                            weglowodany = 77
                        },
                        new
                        {
                            Id = 114,
                            KategoriaId = 9,
                            Nazwa = "Orzechy włoskie",
                            bialko = 16,
                            indeksglikemiczny = 15,
                            kcal = 654,
                            tluszcze = 65,
                            weglowodany = 14
                        },
                        new
                        {
                            Id = 115,
                            KategoriaId = 4,
                            Nazwa = "Kurczak",
                            bialko = 27,
                            indeksglikemiczny = 0,
                            kcal = 239,
                            tluszcze = 14,
                            weglowodany = 0
                        },
                        new
                        {
                            Id = 116,
                            KategoriaId = 5,
                            Nazwa = "Losos",
                            bialko = 20,
                            indeksglikemiczny = 0,
                            kcal = 208,
                            tluszcze = 13,
                            weglowodany = 0
                        },
                        new
                        {
                            Id = 117,
                            KategoriaId = 3,
                            Nazwa = "Jajko",
                            bialko = 6,
                            indeksglikemiczny = 0,
                            kcal = 68,
                            tluszcze = 5,
                            weglowodany = 1
                        },
                        new
                        {
                            Id = 118,
                            KategoriaId = 7,
                            Nazwa = "Czekolada gorzka",
                            bialko = 5,
                            indeksglikemiczny = 22,
                            kcal = 546,
                            tluszcze = 32,
                            weglowodany = 31
                        },
                        new
                        {
                            Id = 119,
                            KategoriaId = 7,
                            Nazwa = "Czekolada mleczna",
                            bialko = 8,
                            indeksglikemiczny = 40,
                            kcal = 535,
                            tluszcze = 30,
                            weglowodany = 58
                        },
                        new
                        {
                            Id = 120,
                            KategoriaId = 3,
                            Nazwa = "Mleko",
                            bialko = 3,
                            indeksglikemiczny = 30,
                            kcal = 42,
                            tluszcze = 2,
                            weglowodany = 5
                        },
                        new
                        {
                            Id = 121,
                            KategoriaId = 8,
                            Nazwa = "Herbata",
                            bialko = 0,
                            indeksglikemiczny = 0,
                            kcal = 1,
                            tluszcze = 0,
                            weglowodany = 0
                        },
                        new
                        {
                            Id = 122,
                            KategoriaId = 8,
                            Nazwa = "Coca-Cola",
                            bialko = 0,
                            indeksglikemiczny = 63,
                            kcal = 42,
                            tluszcze = 0,
                            weglowodany = 11
                        },
                        new
                        {
                            Id = 123,
                            KategoriaId = 8,
                            Nazwa = "Kawa",
                            bialko = 0,
                            indeksglikemiczny = 0,
                            kcal = 1,
                            tluszcze = 0,
                            weglowodany = 0
                        },
                        new
                        {
                            Id = 124,
                            KategoriaId = 1,
                            Nazwa = "Arbuz",
                            bialko = 1,
                            indeksglikemiczny = 70,
                            kcal = 30,
                            tluszcze = 0,
                            weglowodany = 8
                        },
                        new
                        {
                            Id = 125,
                            KategoriaId = 1,
                            Nazwa = "Brzoskwinia",
                            bialko = 1,
                            indeksglikemiczny = 28,
                            kcal = 39,
                            tluszcze = 0,
                            weglowodany = 10
                        },
                        new
                        {
                            Id = 126,
                            KategoriaId = 1,
                            Nazwa = "Kiwi",
                            bialko = 1,
                            indeksglikemiczny = 52,
                            kcal = 61,
                            tluszcze = 0,
                            weglowodany = 15
                        },
                        new
                        {
                            Id = 127,
                            KategoriaId = 1,
                            Nazwa = "Granat",
                            bialko = 1,
                            indeksglikemiczny = 53,
                            kcal = 83,
                            tluszcze = 1,
                            weglowodany = 19
                        },
                        new
                        {
                            Id = 128,
                            KategoriaId = 1,
                            Nazwa = "Śliwki",
                            bialko = 1,
                            indeksglikemiczny = 39,
                            kcal = 46,
                            tluszcze = 0,
                            weglowodany = 11
                        },
                        new
                        {
                            Id = 129,
                            KategoriaId = 1,
                            Nazwa = "Mandarynki",
                            bialko = 1,
                            indeksglikemiczny = 47,
                            kcal = 53,
                            tluszcze = 0,
                            weglowodany = 13
                        },
                        new
                        {
                            Id = 130,
                            KategoriaId = 1,
                            Nazwa = "Czarna porzeczka",
                            bialko = 1,
                            indeksglikemiczny = 25,
                            kcal = 56,
                            tluszcze = 0,
                            weglowodany = 14
                        },
                        new
                        {
                            Id = 131,
                            KategoriaId = 1,
                            Nazwa = "Kumkwat",
                            bialko = 2,
                            indeksglikemiczny = 40,
                            kcal = 71,
                            tluszcze = 0,
                            weglowodany = 16
                        },
                        new
                        {
                            Id = 132,
                            KategoriaId = 1,
                            Nazwa = "Liczi",
                            bialko = 1,
                            indeksglikemiczny = 50,
                            kcal = 66,
                            tluszcze = 0,
                            weglowodany = 17
                        },
                        new
                        {
                            Id = 133,
                            KategoriaId = 1,
                            Nazwa = "Papaja",
                            bialko = 1,
                            indeksglikemiczny = 59,
                            kcal = 43,
                            tluszcze = 0,
                            weglowodany = 11
                        },
                        new
                        {
                            Id = 134,
                            KategoriaId = 1,
                            Nazwa = "Czereśnie",
                            bialko = 1,
                            indeksglikemiczny = 22,
                            kcal = 63,
                            tluszcze = 0,
                            weglowodany = 16
                        },
                        new
                        {
                            Id = 135,
                            KategoriaId = 1,
                            Nazwa = "Nektarynka",
                            bialko = 1,
                            indeksglikemiczny = 32,
                            kcal = 44,
                            tluszcze = 0,
                            weglowodany = 11
                        },
                        new
                        {
                            Id = 136,
                            KategoriaId = 1,
                            Nazwa = "Jeżyny",
                            bialko = 1,
                            indeksglikemiczny = 25,
                            kcal = 43,
                            tluszcze = 1,
                            weglowodany = 10
                        },
                        new
                        {
                            Id = 137,
                            KategoriaId = 1,
                            Nazwa = "Granat",
                            bialko = 1,
                            indeksglikemiczny = 53,
                            kcal = 83,
                            tluszcze = 1,
                            weglowodany = 19
                        },
                        new
                        {
                            Id = 138,
                            KategoriaId = 2,
                            Nazwa = "Papryka czerwona",
                            bialko = 1,
                            indeksglikemiczny = 30,
                            kcal = 31,
                            tluszcze = 0,
                            weglowodany = 7
                        },
                        new
                        {
                            Id = 139,
                            KategoriaId = 1,
                            Nazwa = "Malina",
                            bialko = 1,
                            indeksglikemiczny = 25,
                            kcal = 52,
                            tluszcze = 0,
                            weglowodany = 12
                        },
                        new
                        {
                            Id = 140,
                            KategoriaId = 1,
                            Nazwa = "Truskawka",
                            bialko = 1,
                            indeksglikemiczny = 25,
                            kcal = 32,
                            tluszcze = 0,
                            weglowodany = 8
                        },
                        new
                        {
                            Id = 141,
                            KategoriaId = 2,
                            Nazwa = "Por",
                            bialko = 2,
                            indeksglikemiczny = 15,
                            kcal = 31,
                            tluszcze = 0,
                            weglowodany = 7
                        },
                        new
                        {
                            Id = 142,
                            KategoriaId = 2,
                            Nazwa = "Rzodkiewka",
                            bialko = 1,
                            indeksglikemiczny = 15,
                            kcal = 16,
                            tluszcze = 0,
                            weglowodany = 3
                        },
                        new
                        {
                            Id = 143,
                            KategoriaId = 2,
                            Nazwa = "Dynia",
                            bialko = 1,
                            indeksglikemiczny = 75,
                            kcal = 26,
                            tluszcze = 0,
                            weglowodany = 6
                        },
                        new
                        {
                            Id = 144,
                            KategoriaId = 2,
                            Nazwa = "Kapusta pekińska",
                            bialko = 1,
                            indeksglikemiczny = 10,
                            kcal = 13,
                            tluszcze = 0,
                            weglowodany = 3
                        },
                        new
                        {
                            Id = 145,
                            KategoriaId = 2,
                            Nazwa = "Kalafior",
                            bialko = 2,
                            indeksglikemiczny = 15,
                            kcal = 25,
                            tluszcze = 0,
                            weglowodany = 5
                        },
                        new
                        {
                            Id = 146,
                            KategoriaId = 3,
                            Nazwa = "Mleko krowie",
                            bialko = 3,
                            indeksglikemiczny = 30,
                            kcal = 42,
                            tluszcze = 2,
                            weglowodany = 5
                        },
                        new
                        {
                            Id = 147,
                            KategoriaId = 3,
                            Nazwa = "Ser biały",
                            bialko = 10,
                            indeksglikemiczny = 35,
                            kcal = 98,
                            tluszcze = 5,
                            weglowodany = 4
                        },
                        new
                        {
                            Id = 148,
                            KategoriaId = 3,
                            Nazwa = "Jogurt naturalny",
                            bialko = 10,
                            indeksglikemiczny = 36,
                            kcal = 61,
                            tluszcze = 3,
                            weglowodany = 4
                        },
                        new
                        {
                            Id = 149,
                            KategoriaId = 3,
                            Nazwa = "Twaróg",
                            bialko = 18,
                            indeksglikemiczny = 30,
                            kcal = 103,
                            tluszcze = 5,
                            weglowodany = 3
                        },
                        new
                        {
                            Id = 150,
                            KategoriaId = 9,
                            Nazwa = "Masło",
                            bialko = 1,
                            indeksglikemiczny = 0,
                            kcal = 717,
                            tluszcze = 81,
                            weglowodany = 0
                        },
                        new
                        {
                            Id = 151,
                            KategoriaId = 4,
                            Nazwa = "Kurczak",
                            bialko = 27,
                            indeksglikemiczny = 0,
                            kcal = 239,
                            tluszcze = 14,
                            weglowodany = 0
                        },
                        new
                        {
                            Id = 152,
                            KategoriaId = 4,
                            Nazwa = "Wołowina",
                            bialko = 28,
                            indeksglikemiczny = 0,
                            kcal = 250,
                            tluszcze = 16,
                            weglowodany = 0
                        },
                        new
                        {
                            Id = 153,
                            KategoriaId = 5,
                            Nazwa = "Śledź",
                            bialko = 18,
                            indeksglikemiczny = 0,
                            kcal = 203,
                            tluszcze = 14,
                            weglowodany = 0
                        },
                        new
                        {
                            Id = 154,
                            KategoriaId = 4,
                            Nazwa = "Szynka",
                            bialko = 15,
                            indeksglikemiczny = 0,
                            kcal = 101,
                            tluszcze = 4,
                            weglowodany = 1
                        },
                        new
                        {
                            Id = 155,
                            KategoriaId = 4,
                            Nazwa = "Indyk",
                            bialko = 30,
                            indeksglikemiczny = 0,
                            kcal = 135,
                            tluszcze = 3,
                            weglowodany = 0
                        },
                        new
                        {
                            Id = 156,
                            KategoriaId = 4,
                            Nazwa = "Kiełbasa",
                            bialko = 14,
                            indeksglikemiczny = 0,
                            kcal = 325,
                            tluszcze = 29,
                            weglowodany = 2
                        },
                        new
                        {
                            Id = 157,
                            KategoriaId = 4,
                            Nazwa = "Boczek",
                            bialko = 9,
                            indeksglikemiczny = 0,
                            kcal = 458,
                            tluszcze = 45,
                            weglowodany = 0
                        },
                        new
                        {
                            Id = 158,
                            KategoriaId = 3,
                            Nazwa = "Żółtko jajka",
                            bialko = 17,
                            indeksglikemiczny = 0,
                            kcal = 322,
                            tluszcze = 27,
                            weglowodany = 1
                        },
                        new
                        {
                            Id = 159,
                            KategoriaId = 4,
                            Nazwa = "Wieprzowina",
                            bialko = 21,
                            indeksglikemiczny = 0,
                            kcal = 242,
                            tluszcze = 17,
                            weglowodany = 0
                        },
                        new
                        {
                            Id = 160,
                            KategoriaId = 4,
                            Nazwa = "Kaczka",
                            bialko = 24,
                            indeksglikemiczny = 0,
                            kcal = 337,
                            tluszcze = 27,
                            weglowodany = 0
                        },
                        new
                        {
                            Id = 161,
                            KategoriaId = 4,
                            Nazwa = "Cielęcina",
                            bialko = 21,
                            indeksglikemiczny = 0,
                            kcal = 111,
                            tluszcze = 3,
                            weglowodany = 0
                        },
                        new
                        {
                            Id = 162,
                            KategoriaId = 4,
                            Nazwa = "Baranina",
                            bialko = 22,
                            indeksglikemiczny = 0,
                            kcal = 294,
                            tluszcze = 23,
                            weglowodany = 0
                        },
                        new
                        {
                            Id = 163,
                            KategoriaId = 4,
                            Nazwa = "Kurczak",
                            bialko = 27,
                            indeksglikemiczny = 0,
                            kcal = 239,
                            tluszcze = 14,
                            weglowodany = 0
                        },
                        new
                        {
                            Id = 164,
                            KategoriaId = 4,
                            Nazwa = "Indyk",
                            bialko = 30,
                            indeksglikemiczny = 0,
                            kcal = 135,
                            tluszcze = 3,
                            weglowodany = 0
                        },
                        new
                        {
                            Id = 165,
                            KategoriaId = 3,
                            Nazwa = "Jajko",
                            bialko = 6,
                            indeksglikemiczny = 0,
                            kcal = 68,
                            tluszcze = 5,
                            weglowodany = 1
                        },
                        new
                        {
                            Id = 166,
                            KategoriaId = 5,
                            Nazwa = "Tunczyk",
                            bialko = 26,
                            indeksglikemiczny = 0,
                            kcal = 116,
                            tluszcze = 1,
                            weglowodany = 0
                        });
                });

            modelBuilder.Entity("InsulinResistanceApp.Shared.Uzytkownik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DataUtworzeniaKonta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("HashowaneHaslo")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("Sol")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("resetPasswordToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("resetTokenNiewazny")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Uzytkownicy");
                });

            modelBuilder.Entity("InsulinResistanceApp.Shared.Produkt", b =>
                {
                    b.HasOne("InsulinResistanceApp.Shared.Kategoria", "Kategoria")
                        .WithMany()
                        .HasForeignKey("KategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategoria");
                });
#pragma warning restore 612, 618
        }
    }
}
